apiVersion: v1 # K8S API Version
kind: Pod  # Object Type
metadata: 
 name: nginx 
spec:
 containers: 
 - name: nginx 
   image: nginx:1.7.9 
   volumeMounts:
    - name: persistent-storage
      mountPath: /data/temp
   ports: 
   - containerPort: 80
 - name: springapp
   image: yanivomc/spring-music:latest
   volumeMounts:
    - name: persistent-storage
      mountPath: /app/data
   ports: 
   - containerPort: 8080
 volumes:
  - name: persistent-storage
    emptyDir: {}
